nginx_ssl_certs:
  - name: ca.crt
    value: |
      -----BEGIN CERTIFICATE-----
      ....
      -----END CERTIFICATE-----
  - name: server.crt
    value: |
      -----BEGIN CERTIFICATE-----
      ....
      -----END CERTIFICATE-----
  - name: server.key
    value: |
      -----BEGIN PRIVATE KEY-----
      ....
      -----END PRIVATE KEY-----

nginx_config: |
  upstream backend {
    server {{ hostvars['nginx-2']['ansible_host'] }}:80;
    server {{ hostvars['nginx-3']['ansible_host'] }}:80;
  }
  server {
    listen 80;
    server_name nginx-1.local;
    location / {
      proxy_pass http://backend;
    }
  }